# Location of PopPIPE repository relative to the Snakefile
poppipe_location: .

# Files output by the PopPUNK run
poppunk_rfile: rfiles.txt
poppunk_clusters: database_clusters.csv
poppunk_h5: database.h5
transmission_metadata: transmission_metadata_renamed.csv

# Minimum cluster size to subcluster
min_cluster_size: 6

# ska options
ska:
  fastq_qual: 20
  fastq_cov: 4
  kmer: 31
  single_strand: false
  freq_filter: 0.9

# IQ-TREE options
iqtree:
  enabled: true
  mode: full
  model: 012310+G # +ASC recommended. May replace 012310 with GTR for single strand data

# fastbaps options
fastbaps:
  # Number of hierarchical clustering levels
  levels: 2

# mandrake options
mandrake:
  knn: 50
  perplexity: 25
  maxIter: 100000

# Microreact title, and your contact details
microreact:
  name: SPARC PopPIPE
  website: https://www.bacpop.org
  email: poppunk@poppunk.net
  api_token: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..9Qij00Pptvon4hrn.qB9Fnwkx7ntexak0m0dDYSmrYBCtCPPYqFXOCwtXVLjCnVClVZzwfQ8H0V1B6YBX5pwdinfLwfllrOBGIeVk1E20eVDSrb-XfBsmDPMMa1cv0iYSmFwv1NbW2ecjQxc9zVkVNSyECL3rUkeI5ALs4w.68KLFfjT8WoEGzWn_5ugsA  ## see https://docs.microreact.org/api/access-tokens

# gubbins options
gubbins:
  prefix: gubbins
  tree_builder: iqtree
  min_snps: 3
  min_window_size: 100
  max_window_size: 10000
  iterations: 5

# transphylo options
transphylo:
  w_shape: 10
  w_scale: 0.1
  mcmcIterations: 1000
  startNeg: 0.1
  startOff_r: 1
  startOff_p: 0.5
  startPi: 0.5
  optiStart: 2
  dateT: 0
