# Location of PopPIPE repository relative to the Snakefile
poppipe_location: .

# Files output by the PopPUNK run
poppunk_rfile: ../PopPUNK/without_hash/rfiles.txt
poppunk_clusters: ../PopPUNK/without_hash/mass_database/mass_database_clusters.csv
poppunk_h5: ../PopPUNK/without_hash/mass_database/mass_database.h5

# Minimum cluster size to subcluster
min_cluster_size: 6

# ska options for read sets with "ska fastq"
ska:
  fastq_qual: 20
  fastq_cov: 4

# gubbins options
gubbins:
  prefix: gubbins
  tree-builder: iqtree
  min-snps: 3
  min-window-size: 100
  max-window-size: 10000
  iterations: 10
  dir: /Users/wachsmannj/Documents/pp/PopPIPE/output/strains/{strain}/

# TODO: change dir to global path
# transphylo options
transphylo:
  w_shape: 10
  w_scale: 0.1
  mcmcIterations: 1000
  startNeg: 0.2739726 #100/365
  startOff_r: 1
  startOff_p: 0.5
  startPi: 0.5
  optiStart: 2

# IQ-TREE options
iqtree:
  enabled: true
  mode: full
  model: GTR+ASC+G

# fastbaps options
fastbaps:
  # Number of hierarchical clustering levels
  levels: 2
  # Location of `run_fastbaps`.
  # Find by running `system.file("run_fastbaps", package = "fastbaps")` in R.
  script: run_fastbaps

# mandrake options
mandrake:
  knn: 50
  perplexity: 25
  maxIter: 100000

# Microreact title, and your contact details
microreact:
  name: Listeria PopPIPE
  website: https://www.poppunk.net
  email: poppunk@poppunk.net
  api_token: a1b2c3d4  ## see https://docs.microreact.org/api/access-tokens
