$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  poppipe_location:
    type: string

  poppunk_rfile:
    type: string
  poppunk_clusters:
    type: string
  poppunk_h5:
    type: string

  min_cluster_size:
    type: integer
    minimum: 3

  ska:
    type: object
    properties:
      fastq_qual:
        type: integer
        minimum: 0
        maximum: 100
        default: 20
      fastq_cov:
        type: integer
        minimum: 0
        maximum: 2000
        default: 4

  iqtree:
    type: object
    properties:
      enabled:
        type: boolean
      mode:
        type: string
        pattern: "^(fast|full)$"
      model:
        type: string
    required:
      - enabled
      - mode
      - model

  fastbaps:
    type: object
    properties:
      script:
        type: string
      levels:
        type: integer
        minimum: 1
    required:
      - script
      - levels

  mandrake:
    type: object
    properties:
      perplexity:
        type: number
        minimum: 5
        maximum: 100
      knn:
        type: number
        minimum: 2
      maxIter:
        type: number
        minimum: 10000
        default: 100000
    required:
      - perplexity
      - knn

  microreact:
    type: object
    properties:
      name:
        type: string
      website:
        type: string
      email:
        type: string
      api_token:
        type: string
    required:
      - name
      - website
      - email
      - api_token

required:
  - poppipe_location
  - poppunk_rfile
  - poppunk_clusters
  - poppunk_h5
  - iqtree
  - fastbaps
  - mandrake
  - microreact