$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  poppipe_location:
    type: string

  poppunk_rfile:
    type: string
  poppunk_clusters:
    type: string
  poppunk_h5:
    type: string
  transmission_metadata:
    type: string

  min_cluster_size:
    type: integer
    minimum: 3

  ska:
    type: object
    properties:
      fastq_qual:
        type: integer
        minimum: 0
        maximum: 100
        default: 20
      fastq_cov:
        type: integer
        minimum: 0
        maximum: 2000
        default: 4

  iqtree:
    type: object
    properties:
      enabled:
        type: boolean
      mode:
        type: string
        pattern: "^(fast|full)$"
      model:
        type: string
    required:
      - enabled
      - mode
      - model

  gubbins:
    type: object
    properties:
      prefix:
        type: string
      tree_builder:
        type: string
      min_snps:
        type: integer
        default: 3
      min_window_size:
        type: integer
        default: 100
      max_window_size:
        type: integer
        default: 10000
      iterations:
        type: integer
        default: 10
    required:
      - prefix
      - tree_builder
      - min_snps
      - min_window_size
      - max_window_size
      - iterations

  transphylo:
    type: object
    properties:
      w_shape:
        type: number
        default: 10
      w_scale:
        type: number
        default: 0.1
      mcmcIterations:
        type: integer
        default: 1000
      startNeg:
        type: number
        default: 0.1
      startOff_r:
        type: number
        default: 1
      startOff_p:
        type: number
        default: 0.5
      startPi:
        type: number
        default: 0.5
      optiStart:
        type: number
        default: 2
      dateT:
        type: number
        default: 0

  fastbaps:
    type: object
    properties:
      levels:
        type: integer
        minimum: 1
    required:
      - levels

  mandrake:
    type: object
    properties:
      perplexity:
        type: number
        minimum: 5
        maximum: 100
      knn:
        type: integer
        minimum: 2
      maxIter:
        type: integer
        minimum: 10000
        default: 100000
    required:
      - perplexity
      - knn

  microreact:
    type: object
    properties:
      name:
        type: string
      website:
        type: string
      email:
        type: string
      api_token:
        type: string
    required:
      - name
      - website
      - email
      - api_token

required:
  - poppipe_location
  - poppunk_rfile
  - poppunk_clusters
  - poppunk_h5
  - iqtree
  - fastbaps
  - mandrake
  - microreact
