$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  script_location:
    type: string
  
  poppunk_rfile:
    type: string
  poppunk_clusters:
    type: string
  poppunk_db:
    type: string

  min_cluster_size:
    type: integer
    minimum: 3
  
  iqtree:
    type: object
    properties:
      enabled:
        type: boolean
      mode:
        type: string
        pattern: "^(fast|full)$"
      model:
        type: string
    required:
      - enabled
      - mode
      - model

  fastbaps:
    type: object
    properties:
      script:
        type: string
      levels:
        type: integer
        minimum: 1
    required:
      - script
      - levels

required:
  - script_location
  - poppunk_rfile
  - poppunk_clusters
  - poppunk_db
  - iqtree
  - fastbaps