script_location: scripts

poppunk_rfile: rlist.txt
poppunk_clusters: listeria_clusters.csv
poppunk_db: listeria

min_cluster_size: 6

sketch:
  min_k: 13
  max_k: 29
  k_step: 4
  sketch_size: 10000

iqtree:
  enabled: true
  mode: full
  model: GTR+ASC+G

fastbaps:
  levels: 2
  script: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/fastbaps/run_fastbaps