script_location: scripts

poppunk_rfile: rlist.txt
poppunk_clusters: listeria_new/listeria_poppunk/listeria_db_new_clusters.csv
poppunk_db: listeria_new/listeria.h5

sketch:
  min_k: 15
  max_k: 29
  k_step: 3
  sketch_size: 10000
