name: pp_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python
  - numpy
  - iqtree >=2.0.3
  - rapidnj >=v2.3.2
  - ete3 >=3.1
  - ska >=1.0
  - pp-sketchlib >=2.0.0
  - poppunk >=2.3.0
  - r-fastbaps >=1.0.3
  - mandrake >=1.2.1
