name: pp_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python >=3.7
  - numpy >=1.18
  - iqtree >=2.0.3
  - rapidnj >=v2.3.2
  - ete3 >=3.1.2
  - ska2 =0.3.0
  - pp-sketchlib >=2.0.0
  - poppunk >=2.3.0
  - r-base
  - r-fastbaps =1.0.5
  - mandrake >=1.2.1
  - gubbins >= 3.1.0
  - r-transphylo
  - r-bactdating
  - r-ape
  - r-optparse
  - r-fs