channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - pandas
  - snakemake >=7.0 # NB, snakemake 8 would be preferred, requires python 3.11 (clashes with gubbins)
  - python >=3.7
  - pulp <2.8 # see https://github.com/snakemake/snakemake/issues/2607
  - numpy >=1.18
  - iqtree >=2.0.3
  - rapidnj >=v2.3.2
  - ete3 >=3.1.2
  - ska2 >=0.4.0
  - pp-sketchlib >=2.0.0
  - poppunk >=2.3.0
  - r-base
  - r-fastbaps >=1.0.5
  - mandrake >=1.2.1
  - gubbins >= 3.1.0 # Max python 3.10
  - r-transphylo
  - r-bactdating
  - r-ape
  - r-optparse
  - r-fs